import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import Notification from "@/components/notification";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
=======
>>>>>>> ead45c6 (Initial commit from Create Next App)

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<<<<<<< HEAD
        <Notification />
        <Navbar />
        {children}
        <Footer />
=======
        {children}
>>>>>>> ead45c6 (Initial commit from Create Next App)
      </body>
    </html>
  );
}
